# Generated by Django 3.2.7 on 2021-09-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
